version: '3.7'

services:
  account:
    image: sii/ms:2.0.0
    restart: always
    ports:
      - "7898:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: ms
    ports:
      - "5432:5432"
